export const TYPES = {
  LOGIN: 'LOGIN',
  ADDTOCART: 'ADDTOCART',
  UPDATE: 'UPDATE',
  REMOVEFROMCART: 'REMOVEFROMCART',
  INCREASEQUANTITY: 'INCREASEQUANTITY',
  DECREASEQUANTITY: 'DECREASEQUANTITY'
}
